src/udl/skel/PHP/pylib/lang_php.py
I sure as hell my changes requires some refactoring but my English not that good to call variables better than now.
=> Fixed #203

src/modules/commando/content/ui/pref.xul
Added id attribute to window
FIxed same ids
Without these fixes overlaying this xul through add-ons is impossible because `window` doesn't have the id and groupboxes has the same id's
=> XUL imrpoves

util/docker/Dockerfile
hgsvn package was missinf from the Dockerfile, so it was added to it
=> Dockerfile improved

src/run/koRunService.p.py
When executing a command in the Run service of Komodo using a variable
like %F raises an error if the filepath has spaces in it.
Like an example, when working with the file which path is /home/user/my
project/my file.py and executing the python %F command through the run
service, an error is raised because the command tries to open that
exactly path and not the /home/user/my\ project/my\ file.py.
Through some tests i can tell it works although it hasn't been tested
on Komodo Edit because of some problems with the building process.
=> Fixed an error in the Run service

src/lint/koHTMLLinter.py
Sample input to test this:
if ("missing close-paren should be flagged" {
let x = y;
<% if "ruby complains about bad indentation " %>
alert('foo")
<% end %>
}
You should see a ruby indentation warning, but no JS error messages.  Apply the patch,
and JS problems should appear.
=> 1038: stop assuming all multi-lang files are markup-based

src/components/koInitService.p.py
During upgrade (from 9.3 to 10.0), my Linux machine had a barely used Komodo 9.3 profile, and as such did not have the *~/.komodoide/9.3/XRE/extensions* folder, which caused the upgradeUserSettings function to fail with this error:
```
[2016-06-17 09:05:56,555] [ERROR] koInitService: upgradeUserSettings
Traceback (most recent call last):
File "/home/toddw/install/Komodo-IDE-10/lib/mozilla/components/koInitService.py", line 1494, in upgradeUserSettings
self._upgradeUserDataDirFiles()
File "/home/toddw/install/Komodo-IDE-10/lib/mozilla/components/koInitService.py", line 1475, in _upgradeUserDataDirFiles
ignoreErrors=True)
File "/home/toddw/install/Komodo-IDE-10/lib/mozilla/components/koInitService.py", line 184, in _copy
raise OSError("Source file %r does not exist" % srcFile)
OSError: …
```
=> upgrade: ignore errors (when asked) for source directories that do not exist

src/lint/koCSSExLinter.py
=> Linter: CSS: fixed #1823 (incorrect word for SASS linter popup)

src/chrome/komodo/content/hyperlinks/csscolorpicker.js
Added a fix for #1920 a simple check if it's not a less or sass/scss var.
=> dont show color swatch on less and scss vars, fixes #1920

src/chrome/komodo/locale/en-US/keybindings/keybindings.dtd, src/chrome/komodo/locale/en-US/komodo.dtd, src/chrome/komodo/locale/en-US/pref/pref.dtd
I did not rename any code-specific identifiers though. They are still dedent. Only UX :)
=> Locale: dedent -> unindent; fixed #991

mozilla/build.py
build.py: mozilla-release hg: choose bzip or gzip-v2 if available, else rely on random.
=> Fixed #2449

src/chrome/komodo/content/statusbar.p.js
=> Statusbar: fixed a bug when you can't open the encoding menu for files

src/chrome/komodo/skin/global/chromeless.less
The 10px padding on the menu is slightly too much.  When you move the cursor to the top of the screen, the menu is 2px too low to click on, so you have to move back down slightly.  This change lowers the padding so that you can throw your mouse cursor to the top of the screen and click a menu immediately.
=> Reduce padding for Fitts' law

src/modules/console/content/less/console.less
It's now always in the area of the console widget (80% height of it, but still 200px maximum)
fixed #1315
=> Console: fixed autocomplete popup being under some elements

src/chrome/komodo/content/pref/pref-editsmart.xul
It has an id in the IDE, but not in the Edit version (so I couldn't inject Xemmet prefs in the Edit version)
=> Added an id to Hightlight Variable groupbox

util/black/bk.py
Fixed a typo that shows up in "bk help build".
Changed "underlieing" to "underlying".
=> Fixed a typo

src/chrome/komodo/skin/codeintel.p.css
I suppose this might be "included" as part of a bigger template but from running Komodo and looking at the startup logs it seems like this is also dynamically interpreted as a syntax error. I assume its not actually doing anything due to this so I think it should be removed.
=> Remove typo?

src/chrome/komodo/content/komodo.p.js, src/chrome/komodo/skin/images/toolbox/command.svg
- Remove undefined function call resulting in:
```
[ERROR] console-logger: ReferenceError: authenticateUser is not defined (2) in chrome://komodo/content/komodo.js:477
```
- Remove non-visible SVG element resulting in this error:
```
[WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
```
=> Minor Fixes from Error Log

src/chrome/komodo/content/bindings/scintilla.p.xml, src/chrome/komodo/content/bindings/views-editor.p.xml, src/chrome/komodo/content/bindings/views-multi.xml, src/views/koDocument.py
- Don't allow more than 2 splits.  Jump back to existing view.
- I don't think there can be more than 2 split views, but let me know if it's possible and I'll remove this change.
- <strike>Cheap fix for Komodo/KomodoEdit#231</strike>
- <strike>I couldn't figure out how split view works to sync the views.  This at least prevents the bug.  If you can easily explain how that syncing works, I can look into a better fix.</strike>
- Closes Komodo/KomodoEdit#231
=> Split View Updates

src/chrome/komodo/content/bindings/views-editor.p.xml
When you use Save As on an executable file, the new file is not longer executable.  This solves that.
=> Update File Permissions on Save As

src/chrome/komodo/content/bindings/views-buffer.p.xml
- `lastPosition` wasn't initialized.
- Very minor performance updates.  They probably don't add up to much:
- Don't check `require` when not needed.
- Consolidate two `this.lastCharAdded` checks into one.
- Add `scan_document` request via timeout even when line are added/removed.  This prevents duplicate requests when you hit Enter a few times or when you hold down Cmd/Ctrl-Z to undo a lot of changes with newlines.
=> Minor Performance Updates

src/codeintel/lib/codeintel2/citadel.py, src/codeintel/lib/codeintel2/database/langlibbase.py, src/codeintel/lib/codeintel2/database/multilanglib.py, src/codeintel/lib/codeintel2/lang_css.py, src/codeintel/lib/codeintel2/lang_javascript.py, src/codeintel/lib/codeintel2/lang_perl.py, src/codeintel/lib/codeintel2/lang_python.py, src/codeintel/lib/codeintel2/lang_ruby.py, src/codeintel/lib/codeintel2/util.py, src/codeintel/src/komodo/koCodeIntel.py, src/udl/skel/PHP/pylib/lang_php.py
- Add missing db.corruption param to multilanglib.py. Addresses Komodo/KomodoEdit#2228
- Exclude directories sooner to reduce unnecessary filesystem calls and later filtering.
- Update PHP, Javascript, and CSS to better respect excludes.  Addresses #3591
- Other languages might need the same treatment.  I only worked on the primary ones I use.
=> CodeIntel2 Optimizations & Corruption Call Fix

src/chrome/komodo/content/find/embedded.p.xul, src/chrome/komodo/content/find/find2.p.js
1. Disable access keys on window blur.  Closes #3706.
One downside to this is if people are using the access keys like Find Next while focused on the editor.  I'm not sure if people do that much.
2. Don't rebuild HTML with each open.
I removed this when running into an issue with an approach for 1 that I didn't go with, so I can add it back in if you want.  However, I didn't see why it was needed.  I see it was added in e8e1b2f9f5179be90715a3a4f94b7ff4e87f9b60 to deal with #669 and #710.  I was able to open Find multiple times and use Find All with no issues.
3. Add Shift-Enter for reverse search.
=> Find Updates

src/codeintel/lib/codeintel2/udl.py
- Closes #3712
- I'm pretty certain that the intent of the original code was to strip styles not in the current language, but it was including the first non-matching style.
=> Fix UDL Text Chunks

src/main/xre/app/profile/komodo.p.js
@cgchoffman I took your hint on `accessibility.tabfocus_applies_to_ul` and was able to get this to work.  Not sure if you have a fix too, so feel free to close this if you do.
=> Fix Tabbing Between Fields on Mac

src/udl/skel/PHP/pylib/lang_php.py
The lowercase was adding in https://github.com/Komodo/KomodoEdit/pull/255.  I'm not positive, but I think that maybe lowercase was needed on https://github.com/Komodo/KomodoEdit/pull/255/files#diff-dc815a8023784357f18d19a1c5031ee2R1545, but added to the PHPDoc text too.
=> Don't Lowercase PHPDoc Types

src/chrome/komodo/content/find/find2.p.js, src/chrome/komodo/content/library/mru.js
When using find in project, the new Include filter results in the following error log message:
```
[WARNING] ko.mru: MRU_add: warning: no entry: prefName='find-includeFiletypesMru', entry=''
```
It's normal that an empty string should be saved there.
=> Remove Empty MRU Warning

src/chrome/komodo/content/hyperlinks/gotodefinition.js, src/codeintel/lib/codeintel2/oop/controller.py, src/codeintel/lib/codeintel2/tree_php.py
- Comment out unused calltip variables
- Only log warning messages. Reduces excessively large error log messages
- Don't try to look up PHP keywords. They'll just result in an error
This addresses #3658 by preventing keyword lookups and limiting the messages logged.  However, I'm not sure if the issue should be closed in case @th3coop had plans to work on improving the underlying lookup.
=> CodeIntel Improvements

src/chrome/komodo/content/run/runOutputPane.xul, src/chrome/komodo/content/run/runOutputWindow.js, src/chrome/komodo/locale/en-US/komodo.dtd
=> Comment output clear option

src/udl/skel/PHP/pylib/lang_php.py
This extends #3744 to handle this:
```php
class MyClass
{
/**
* @return self
*/
function a()
{
return $this;
}
}
// Works
$c = new MyClass();
$c->a()->
// Doesn't work before this pull request
(new MyClass())->a()->
```
=> Handle Chained Methods with Parenthesis

src/python-sitelib/pythonVersionUtils.py
Create a file called `notnode.js` with:
```javascript
let a = $("#a");
a.on("click", function() {
});
```
Komodo detects it as Node.js.  This change uses jQuery functions to help it detect JavaScript.
Note: You may need to clear `doc-state.xmlc` to test.
=> Use jQuery to Detect Javascript

src/chrome/komodo/content/bindings/views-multi.xml, src/modules/openfiles/content/openfiles.js
1. Moving a file to a split with the same file resulted in exception.
2. Moving a file between tabs resulted in access to koDoc while null.
=> Fix Split View Issues

src/chrome/komodo/content/commandsOverlay.p.xul, src/chrome/komodo/content/komodo.p.xul, src/chrome/komodo/locale/en-US/komodo.dtd, src/editor/koLanguageCommandHandler.p.py
- This can be useful if you are in the middle of a function and want to jump up through the code to find parent conditionals and the parent function.  Also useful in large HTML blocks of text to get to the parent tag.
- Python doesn't have braces, so next and previous could be useful in place of the jump to matching brace function you can do in other languages.
=> Jump to Code Fold

src/codeintel/lib/codeintel2/tree_php.py
@th3coop, I tried the new nightly and noticed a bug with my keyword update in #3730.  PHP keywords like `isset(...)`, `empty(...)`, etc. did not have tooltips.  This fixes that while still limiting the amount of work done processing keywords.
=> Fix Missing Codeintel on PHP Keywords

src/udl/skel/PHP/pylib/lang_php.py
Solves this issue:
```php
function test(\MyNs\MyClass $a)
{
$a-> // Class lookup fails. Looks for MyClass, not \MyNs\MyClass
}
```
=> Fix PHP Namespace Argument

src/udl/skel/PHP/pylib/lang_php.py
- Handle over 200 characters for arguments better.
- Fix issue where parenthesis in arguments caused trigger to not work.
- Add a comma after the last argument in each `array_push` line.  Comments indicated places this branch fixes.
```php
<?php
$tmp = [];
array_push($tmp, new LogicException()); // Works
array_push($tmp, rand( ) + 5); // Works
array_push($tmp, rand() + 5); // Doesn't work.
array_push($tmp, strtolower('a')); // Doesn't work.
array_push(
$tmp,
// Each argument plus newline is 27 characters. This line itself also takes up around 100 characters
strtolower('0123456789'),
strtolower('0123456789'),
strtolower('0123456789'),
strtolower('0123456789') // Stops working here
);
array_push($tmp,
new \MyVeryLongNamespace\MyVeryLongNamespace2\MyVeryLongNamespace3\MyClass(),
new …
```
=> Make PHP Calltips More Robust

src/udl/skel/PHP/pylib/lang_php.py
- PHP 7.0 return type declarations.
- PHP 7.4 typed properties.
```php
// PHP 7.0 return type declarations
function getLe(): LogicException
{}
function getLe2() : ?LogicException
{}
function getLe3() : \LogicException
{}
$le1 = getLe();
//$le1->
$le2 = getLe2();
//$le2->
$le3 = getLe3();
//$le3->
// PHP 7.4 typed properties
class PropTypeClass
{
public LogicException $propLe1 = null;
public ?LogicException $propLe2 = null;
public ?\LogicException $propLe3 = null;
public int $propInt = 0;
}
$ptc = new PropTypeClass();
//$ptc->propLe1->
```
This will likely have a merge conflict with #3770, but it should be an easy fix.
=> PHP 7 Types

src/codeintel/lib/codeintel2/oop/driver.py, src/codeintel/lib/codeintel2/tree_php.py, src/udl/skel/PHP/pylib/lang_php.py
- Use FQN for PHP types
- Skip outdated trg-from-pos requests.
- For large files, trg-from-pos requests can back up as you type. I can't think of any reason why we'd need to process a request if we got a newer request for a new position.
- PSR4 updates
- Allow filenames like MyClass.class.php
- When doing PSR4 lookup, only concider paths that match namespace
- Do not look at global scope with doing PSR4 lookups
- Use scandir for PHP import lookup.
=> PHP CodeIntel Updates

src/udl/skel/PHP/pylib/lang_php.py
This handles completions on the commented out lines:
```php
/** @var LogicException[] */
$arr1d = [new LogicException()];
$idx = 0;
//$arr1d[0]->
//$arr1d[$idx]->
/** @var LogicException[] */
$arr2d = [[new LogicException()]];
//$arr2d[0][0]->
```
=> Handle Object Member Completion on Array Index

src/chrome/komodo/content/bindings/views-editor.p.xml, src/modules/breadcrumbs/content/bootstrap.js, src/modules/breadcrumbs/content/sdk/breadcrumbs.js
- Closes #3775
- Use event delegation instead of individual event handlers.
- Make sure to remove event listeners on close.
- Unset variables on close (not sure if it helps prevent memory leaks or not.
I still see a line for breadcrumbs in memory usage after closing all files, but at least it seems a little smaller than before.
=> Try To Reduce Memory Usage of Breadcrumbs

src/codeintel/lib/codeintel2/tree_php.py
I introduced a bug in #3781.  I'm not exactly sure how to trigger it, but I saw this exception in the error log after all code intel stopped working.
```
[2019-12-17 09:33:49,457] [ERROR] codeintel.tree: Unexpected error with evaluator: 'taxCartItem.getSalesTaxOriginAddress' at SalesTaxHelper.class.php#1008
Traceback (most recent call last):
File "/Applications/Komodo Edit 11.app/Contents/Resources/python/komodo/codeintel2/tree.py", line 321, in eval
calltips = self.eval_calltips()
File "/Applications/Komodo Edit 11.app/Contents/Resources/python/komodo/codeintel2/tree_php.py", line 358, in eval_calltips
hit = self._hit_from_citdl(expr, start_scope)
File "/Applications/Komodo Edit 11.app/Contents/Resources/python/komodo/codeintel2/tree_php.py", line 946, in _hit_from_citdl
hits = …
```
=> Fix Number of Tokens Consumed in PHP

src/codeintel/lib/codeintel2/tree_php.py
According to [PHPDoc](https://docs.phpdoc.org/latest/guides/types.html), `@return static` should return  "An object of the class where this value was consumed, if inherited it will represent the child class. (see late static binding in the PHP manual)."  This change handles that.
@th3coop, not sure if you want to merge this since CodeIntel is different from IDE.
Here's sample code:
```php
class Base
{
public $baseVar1;
public $baseVar2;
/**
* @return static
*/
public function getInstance()
{
return new static();
}
}
class Child extends Base
{
public $childVar1;
public $childVar2;
}
//$c = new Child();
$c = Child::getInstance();
$c-> // This should return 4 class variables, but only returns the Base class ones
```
=> Handle `@return static` in PHP

src/lint/koPythonLinter.py
pep8 displays a warning when it runs. This warning is printed on stderr, so Komodo acts as if pep8 returned an error.
To make pep8 work again, I changed just one thing:
Komodo does not check pep8 stderr anymore but it checks the return code of pep8.
See https://github.com/Komodo/KomodoEdit/issues/3860
=> Python syntax checking: Change the way of checking that pep8 ran well

contrib/paramiko/paramiko/channel.py
There is a small typo in contrib/paramiko/paramiko/channel.py.
Should read `execute` rather than `exectue`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, exectue -> execute
