src/chrome/komodo/locale/en-US/komodo.dtd

https://github.com/Komodo/KomodoEdit/issues/23

Fixed overriding komodoBugDatabase.tooltiptext

---

src/codeintel/lib/codeintel2/tree_php.py

resolves this issue:
https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/477

correctly resolve methods returning "$this"

---

src/modules/spellcheck/content/koSpellCheck.xul

Fixed #489

---

src/udl/udl/csslex.udl

added the region folding as descibed here #715 for css.(now from a fresh fork)

added css region folding

---

src/udl/Conscript
src/udl/skel/JSERB/components/koJSERB_UDL_Language.py
src/udl/udl/jserb-mainlex.udl
src/udl/udl/ruby2js.udl

Add support for *.js.erb files

1043 - Add JSERB UDL

---

README.md

Updated Building Complications section

---

src/udl/udl/phplex.udl

Fixed #1052; added //Region support for PHP

---

src/codeintel/lib/codeintel2/constants_css3.py

CSS: added pointer-events property; fixes #1090

---

src/chrome/komodo/content/colorpicker/Conscript
src/chrome/komodo/content/colorpicker/colorpicker.html
src/chrome/komodo/content/colorpicker/colorpicker.js
src/chrome/komodo/content/colorpicker/colorpicker.xul
src/chrome/komodo/content/colorpicker/xpcom_colorpicker.js
src/chrome/komodo/skin/Conscript
src/chrome/komodo/skin/colorpicker/colorpicker.less
src/chrome/komodo/skin/colorpicker/wrapper.less

ColorPicker: open it using XULWrapper; fixed #1885

---

src/modules/notify/skin/notify.less

Modules: Notify: description color is now state-foreground; fixed #1494

---

src/codeintel/lib/codeintel2/constants_css2.py

Codeintel: CSS: added posititon: sticky

---

mozilla/build.py

Fixed building proccess for non-as network

---

src/samples/tools/HTML/_A_URI_Link.komodotool
src/samples/tools/HTML/_A_URI_Link_w_Dialog.komodotool
src/samples/tools/HTML/_form_Form_w_Dialog.komodotool
src/samples/tools/HTML/_input_Form_Input_w_Dialog.komodotool
src/samples/tools/HTML/_option_Form_Option_w_Dialog.komodotool
src/samples/tools/HTML/_p_Paragraph_w_Dialog.komodotool
src/samples/tools/HTML/_select_Form_Select_w_Dialog.komodotool
src/samples/tools/HTML/_textarea_Form_Text_Area_w_Dialog.komodotool

Toolbox: changed <A> to <a>, w/Dialog to w/ Dialog; fixed #2433

---

src/modules/scope_files/content/commands.js

Commando: Files Scope: added open in places item, fixes #2401

---

src/chrome/komodo/content/project/projectManager.p.js

Projects: create project in current Places directory; fixed #1813

---

src/chrome/komodo/content/browse.js

Some of them were not working at all and just redirecting to the komodoide landing page.

Fixed links to different Komodo resources (community, packages, etc.)

---

src/chrome/komodo/content/pref/pref-syntax-checking.js
src/chrome/komodo/content/pref/pref-syntax-checking.xul
src/chrome/komodo/locale/en-US/pref/pref.dtd
src/lint/Conscript
src/lint/koRubocopLinter.py

Ruby: Lint: added Rubocop linter

---

src/codeintel/lib/codeintel2/database/langlib.py
src/codeintel/lib/codeintel2/database/multilanglib.py

- Closes Komodo/KomodoEdit#3659

Fix Deleted Multilanglib Language Issue

---

src/modules/commando/content/sdk/controller.js

How long has it been? 2 years? 😄

Commando: removed the code we should not have seen

---

src/chrome/komodo/content/find/find2.p.js
src/chrome/komodo/content/library/mru.js

- Closes Komodo/KomodoEdit#2437
- Closes Komodo/KomodoEdit#3596

Allow blank replacement in MRU

---

src/chrome/komodo/content/find/find_functions.js
src/chrome/komodo/skin/global/icons.less

- Closes Komodo/KomodoEdit#2639
- Fixes icon for show all results.

Replace All Results Fix

---

src/chrome/komodo/content/sdk/editor.js

Make Sure Bookmarks Are Deleted

---

mozilla/patches-new/mozilla-35.0/cocoa/mojave-dropdown-missing-1468053-mozbug.patch

- Closes #3648
- I'm not entirely sure if this is how you apply the patches, but it seems to work.

Fix Mojave Dropdowns

---

src/chrome/komodo/content/find/embedded.p.xul
src/chrome/komodo/content/find/find2.p.js
src/find/koFindContext.py
src/find/koIFindContext.idl
src/projects/koProject.p.py

Allow extra include/exclude filters in project searches

---

src/editor/koLanguageCommandHandler.p.py
src/python-sitelib/reflow.py

Reflow Block Comments

---

src/chrome/komodo/content/bindings/views-editor.p.xml

Fix minimap pref observer

---

src/chrome/komodo/content/codeintel/codeintel.p.js
src/chrome/komodo/content/find/find2.p.js
src/chrome/komodo/content/views.p.js
src/chrome/komodo/skin/global/components/scrolltabs.less
src/find/koFinder.py
src/find/koIFinder.idl
src/modules/openfiles/content/openfiles.js

- Fix #3655 
- Add CSS for current tab
- Fix open files variable name
- Other javascript warning handling

Find Case Sensitivity Fix, Current Tab CSS, & Minor Fixes

---

src/udl/skel/PHP/pylib/lang_php.py

Fix PHP Array Completion Empty String Error

---

src/udl/skel/PHP/pylib/lang_php.py

That was easier than anticipated.  Closes #3737

Bitwise NOT Fix

---

src/codeintel/Conscript
src/codeintel/lib/codeintel2/catalogs/smarty2.cix

Based on https://github.com/smarty-php/smarty/blob/Smarty2/libs/Smarty.class.php

Smarty CIX

---

src/codeintel/lib/codeintel2/parseutil.py
src/codeintel/lib/codeintel2/tree_php.py
src/udl/skel/PHP/pylib/lang_php.py

PHP Array Fixes

---

src/udl/skel/PHP/pylib/lang_php.py

This gets the following completions to work.  Previously, they'd result in `ERROR: evaluating '()'...`
```php
(new LogicException())->
```
```php
$c = new LogicException();
$c->
```
Note that if you put this right after a `<?php` tag, it results in a lookup of `php()`, instead of `()`, so this branch won't fix it.  I though of checking for `()` or `php()`, but wasn't sure if that would be safe.

Handle Arbitrary Parenthesis And Object Member Completion

---

src/chrome/komodo/content/project/peSnippet.js

It's all in the linked ticket.
https://www.pivotaltracker.com/story/show/165873124

Snippets fail to insert in Perl and Ruby files. Fixes #3723

---

src/modules/scope_openfiles/content/openfiles.js

- Splits search into words and checks for words.
- Favors words in the filename.

Improved Openfiles Scope Search

---

src/udl/skel/Smarty/pylib/lang_smarty.py

Smarty Completions

---

src/modules/commando/content/sdk/commando.js

Commando: change tip when selecting using mouse; fixed #2507

---

src/chrome/komodo/content/komodo.p.xul
src/chrome/komodo/locale/en-US/komodo.dtd

Added 'Close All' action in tab context menus; fixed #1817

---

src/codeintel/lib/codeintel2/oop/driver.py

Only Cache Last 2 Buffers

---

src/codeintel/lib/codeintel2/tree_php.py

- Closes #3780
- It's probably best to look at the changes ignoring whitespace (https://github.com/Komodo/KomodoEdit/pull/3781/files?w=1).

Look Up Type Inference on PHP Parent

---

src/codeintel/lib/codeintel2/stdlibs/php-7.0.cix

Add mysqli Back to PHP 7.0

---

src/codeintel/lib/codeintel2/tree_php.py

Fix PHP Interface Inheritance Bug

---

src/codeintel/lib/codeintel2/database/langlib.py

Write Dirty res_index To Disk

---

docs/Linux_build_guide.md

@th3coop Did i make any other typos?

Fix typo in build guide

---

src/udl/skel/PHP/pylib/lang_php.py

Fix PHP Catch Statement CodeIntel

---

src/udl/skel/Smarty/pylib/lang_smarty.py

Fix Smarty Double Dollar Sign

---

src/codeintel/lib/codeintel2/tree_php.py
src/udl/skel/PHP/pylib/lang_php.py

- Closes #3896.
- Autocompletes namespaces from existing namespaces or current file path.

PHP Namespace Completion
